### ISSUE TITLE
Laguerre-Gaussian beam doesn't work with meep 1.9.0

### ISSUE THREAD

**Issue by xj361685640** [DanielKotik/Optical-beams-MEEP#2]
Here is the output information

mpiexec -n 8 meep e_z=0 e_y=1 freq=5 LaguerreGauss3d.ctl

Using MPI version 3.1, 8 processes
command-line param: e_z=0
command-line param: e_y=1
command-line param: freq=5

start time: Fri May 10 09:57:04 2019
Gauss spectrum (cartesian): 0.6347225159862774
Gauss spectrum (spherical): 2.3981973818259543e-8

L-G spectrum   (cartesian): 0.016907581994799106-0.006752644114666309i
L-G spectrum   (spherical): 1.61036015580364e-24+2.6299177149278234e-8i

integrand      (cartesian): 0.01237493696893364+0.0022382324370958263i
integrand      (spherical): -8.908123979652118e-7+1.1204027172148073e-5i

psi            (cartesian): 0.6060939710665376-1.7435922978423426i
psi            (spherical): 0.5341009898668722-1.7119280296995554i

Specified variables and derived values: 
n1:    1.0
n2:    1.54
chi:   45.0 [degree]
incl.: 45.0 [degree]
kw_0:  8
kr_w:  0
k_vac: 31.41592653589793
vortex charge: 2
Jones vector components: (e_z=0, e_y=1) ---> p-polarisation
degree of linear   polarisation at pi/4: 0
degree of circular polarisation: 0

Initializing structure...
Working in 3D dimensions.
Computational cell is 5 x 5 x 4 with resolution 77
     block, center = (2.5,-2.5,0)
          size (1e+20,7.07107,1e+20)
          axes (0.707107,0.707107,0), (-0.707107,0.707107,0), (0,0,1)
          dielectric constant epsilon diagonal = (2.3716,2.3716,2.3716)
subpixel-averaging is 35.9121% done, 7.14225 s remaining
subpixel-averaging is 72.6905% done, 1.50484 s remaining
subpixel-averaging is 34.3034% done, 7.66376 s remaining
subpixel-averaging is 67.5178% done, 1.93616 s remaining
subpixel-averaging is 36.3081% done, 7.01777 s remaining
subpixel-averaging is 71.5025% done, 1.59486 s remaining
time for set_epsilon = 48.3139 s

Meep: using complex fields.

Meep is running but seems to stick here.

**Comment by DanielKotik** [comment]
This is an expected behavior, since the initial field configuration is calculated at this step within `(set! sources ...)`. This involves an integration `(amp-func (psi_spherical ... ))`,  which is however a rather slow routine. 

Unfortunately the print statement `"\nCalculating inital field configuration. This will take some time...\n\n"` is triggered _after_ computing the initial field configuration. I was not able to align these  chronologically.

For testing purposes i recommend setting `relerr` to `0.001` and `maxeval` to `1000` as well as using a simple Gaussian beam, i.e.  `m_charge`  is  zero.

All scripts are tested with meep v1.7.0.
